version: '3.7'
services:
  mariadb:
    image: mariadb:10.3
    container_name: mdblouis
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=maildb

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: pmalouis
    environment:
      - PMA_HOST=mariadb
    ports:
      - 8080:80
    depends_on:
      - mariadb

  mailhog:
    image: mailhog/mailhog
    container_name: mhlouis
    ports:
      - 1025:1025
      - 8025:8025

  php-apache:
    build: .
    volumes:
      - ./DockerProjetLouis:/var/www/html
    ports:
      - 8081:80
    depends_on:
      - mariadb
